## Included once from nginx's http context.

access_log off;

upstream galata_server {
  server 127.0.0.1:3000;
  keepalive 16;
}

upstream galata_dev_server {
  server 127.0.0.1:3001;
  keepalive 16;
}
